// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyProject9.Dbcontext;

#nullable disable

namespace MyProject9.Migrations
{
    [DbContext(typeof(Orders))]
    partial class OrdersModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyProject9.Entities.Contact", b =>
                {
                    b.Property<Guid>("cusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ContactId")
                        .HasColumnType("int");

                    b.Property<int>("phone")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.HasKey("cusId");

                    b.ToTable("contacts");
                });

            modelBuilder.Entity("MyProject9.Entities.Customer", b =>
                {
                    b.Property<Guid>("cusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cusId");

                    b.ToTable("customers");
                });

            modelBuilder.Entity("MyProject9.Entities.Customerid", b =>
                {
                    b.Property<Guid>("cusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CustomercusId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("drivinglicense")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("cusId");

                    b.HasIndex("CustomercusId");

                    b.ToTable("customerids");
                });

            modelBuilder.Entity("MyProject9.Entities.LineItem", b =>
                {
                    b.Property<int>("Orderid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Orderid"));

                    b.Property<int>("OrderLine")
                        .HasColumnType("int");

                    b.Property<int>("proid")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("Orderid");

                    b.ToTable("Lineitems");
                });

            modelBuilder.Entity("MyProject9.Entities.OrderData", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<Guid>("cusId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OrderId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("MyProject9.Entities.product", b =>
                {
                    b.Property<int>("proid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("proid"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("price")
                        .HasColumnType("int");

                    b.HasKey("proid");

                    b.ToTable("products");
                });

            modelBuilder.Entity("MyProject9.Entities.Customerid", b =>
                {
                    b.HasOne("MyProject9.Entities.Customer", null)
                        .WithMany("customerids")
                        .HasForeignKey("CustomercusId");
                });

            modelBuilder.Entity("MyProject9.Entities.Customer", b =>
                {
                    b.Navigation("customerids");
                });
#pragma warning restore 612, 618
        }
    }
}
